Repository fleekxyz/non-fungible-apps, pull requests merged in 2023-01, with the labels that each got.

#65 fix: refetching queries
  ui/src/index.tsx
  ui/src/views/home/list.tsx
Labels: frontend

#66 fix: broken json
  ui/src/integrations/ethereum/lib/fleek-erc721.ts
  ui/src/views/detail/detail.tsx
Labels: frontend

#70 Initialize contract SVG code with placeholder base
  contracts/FleekERC721.sol
  hardhat.config.ts
  test/FleekERC721.ts
  test/foundry/apps.t.sol
Labels: enhancement, test environment, contract

#67 refactor: UI improvements
  .husky/lint-staged.config.json
  ui/package.json
  ui/src/components/attributes-detail/attributes-detail.tsx
  ui/src/components/card/card-attributes.tsx
  ui/src/components/card/card-site.tsx
  ui/src/components/icon/custom/index.ts
  ui/src/components/icon/custom/metamask-icon.tsx
  ui/src/components/icon/icon-types.tsx
  ui/src/components/icon/icon.tsx
  ui/src/components/icon/index.ts
  ui/src/components/wallet-button/index.ts
  ui/src/components/wallet-button/wallet-button.tsx
  ui/src/components/wallet-button/wallet.utils.ts
  ui/src/theme/foundations/colors.ts
  ui/src/theme/foundations/index.ts
  ui/src/theme/index.ts
  ui/src/views/detail/detail.tsx
  ui/src/views/mint-site/mint-site.tsx
  ui/yarn.lock
Labels: frontend

#75 chore: add tailwind and stitches
  ui/.eslintrc.js
  ui/.storybook/main.js
  ui/.storybook/preview-head.html
  ui/.storybook/preview.js
  ui/index.html
  ui/package.json
  ui/postcss.config.js
  ui/src/app.tsx
  ui/src/index.tsx
  ui/src/stories/Button.stories.tsx
  ui/src/stories/Button.tsx
  ui/src/stories/button.css
  ui/src/styles.css
  ui/src/theme/stitches/foundations/colors.ts
  ui/src/theme/stitches/foundations/index.ts
  ui/src/theme/stitches/globals.ts
  ui/src/theme/stitches/index.ts
  ui/src/theme/stitches/themes.ts
  ui/tailwind.config.js
  ui/yarn.lock
Labels: frontend

#64 docs: fix mistakes in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#88 feat: svg preview test screen
  ui/package.json
  ui/src/app.tsx
  ui/src/views/svg-test/index.ts
  ui/src/views/svg-test/svg-test.tsx
  ui/yarn.lock
Labels: frontend

#79 test: foundry tests for access points
  contracts/FleekERC721.sol
  test/foundry/apps.t.sol
Labels: test environment

#84 chore: input component
  ui/src/components/core/icon/icon-library.tsx
  ui/src/components/core/input/index.ts
  ui/src/components/core/input/input-file.tsx
  ui/src/components/core/input/input.stories.tsx
  ui/src/components/core/input/input.ts
  ui/src/components/form/form.stories.tsx
  ui/src/components/form/form.styles.ts
  ui/src/components/form/form.tsx
  ui/src/components/form/index.ts
  ui/src/components/index.ts
  ui/src/components/layout/flex.styled.tsx
  ui/src/theme/foundations/spacing.ts
  ui/src/theme/globals.ts
  ui/src/theme/themes.ts
  ui/src/views/home/home.tsx
Labels: frontend

#72 feat: subgraph setup for the FleekNFA contracts
  .env.example
  .gitignore
  deployments/mumbai/FleekERC721.json
  deployments/mumbai/solcInputs/c05a9ff4c654910b408b84a2af4f1989.json
  hardhat.config.ts
  package.json
  scripts/verify-polyscan.js
  subgraph/README.md
  subgraph/examples/query/.graphclientrc.yml
  subgraph/examples/query/README.md
  subgraph/examples/query/main.ts
  subgraph/examples/query/package.json
  subgraph/examples/query/queries.graphql
  subgraph/examples/query/yarn.lock
  subgraph/networks.json
  subgraph/package.json
  subgraph/schema.graphql
  subgraph/src/fleek-nfa.ts
  subgraph/subgraph.yaml
  subgraph/tests/fleek-nfa-utils.ts
  subgraph/tests/fleek-nfa.test.ts
  subgraph/tsconfig.json
  subgraph/yarn.lock
  yarn.lock
Labels: enhancement, contract

#76 chore: prepare the contracts to be upgradable using openzeppelin proxy plugin
  .gitignore
  .openzeppelin/polygon-mumbai.json
  README.md
  contracts/FleekAccessControl.sol
  contracts/FleekERC721.sol
  deploy/local_deploy.js
  deploy/mumbai_deploy.js
  deployments/mumbai/.chainId
  deployments/mumbai/FleekERC721.json
  deployments/mumbai/proxy.json
  deployments/mumbai/solcInputs/0c2e3cb4979e1bddbff96ad838dc1107.json
  deployments/mumbai/solcInputs/0ee8c4d44ebad02e2364970b68450c98.json
  deployments/mumbai/solcInputs/b88731ab6401d18abef5bd8425a23961.json
  hardhat.config.ts
  package.json
  scripts/deploy.js
  scripts/mint.js
  scripts/tokenURI.js
  scripts/util.js
  scripts/utils/deploy-store.js
  scripts/utils/file.js
  scripts/utils/proxy-store.js
  test/FleekERC721.ts
  test/deploy/proxy-store.ts
  test/deploy/proxy.ts
  test/foundry/apps.t.sol
  yarn.lock
Labels: contract
