Repository fleekxyz/non-fungible-apps, pull requests merged in 2023-04, with the labels that each got.

#200 feat: UI create card list component
  ui/graphql/queries.graphql
  ui/src/components/index.ts
  ui/src/components/nfa-card/index.ts
  ui/src/components/nfa-card/nfa-card.styles.ts
  ui/src/components/nfa-card/nfa-card.tsx
  ui/src/views/explore/list-nfas/nfa-list/nfa-list.tsx
  ui/src/views/mint/nft-card/svg-preview.tsx
Labels: enhancement, frontend

#202 feat: explore pagination view and loading skeletons
  ui/src/components/layout/index.ts
  ui/src/components/layout/skeleton.styles.ts
  ui/src/components/nfa-card/index.ts
  ui/src/components/nfa-card/nfa-card-skeleton.tsx
  ui/src/components/nfa-card/nfa-card.styles.ts
  ui/src/hooks/index.ts
  ui/src/hooks/use-window-scroll-end.ts
  ui/src/providers/apollo-provider.tsx
  ui/src/views/explore/list-nfas/nfa-list/nfa-list.tsx
Labels: enhancement, frontend

#140 feat: sc 121 - serverless boilerplate
  .eslintignore
  .eslintrc.js
  .prettierignore
  package.json
  serverless/.gitignore
  serverless/README.md
  serverless/package.json
  serverless/serverless.yaml
  serverless/src/functions/builds/handler.ts
  serverless/src/functions/builds/index.ts
  serverless/src/libs/api-gateway.ts
  serverless/src/libs/handler-resolver.ts
  serverless/src/libs/lambda.ts
  serverless/tsconfig.json
  serverless/yarn.lock
  yarn.lock
Labels: mvp, backend, deployment

#208 bug: UI colors not showing up on firefox for nfa
  ui/src/components/index.ts
  ui/src/components/nfa-card/nfa-card.tsx
  ui/src/components/nfa-preview/index.ts
  ui/src/components/nfa-preview/nfa-preview.tsx
  ui/src/theme/themes.ts
  ui/src/views/mint/nfa-step/form-step/fields/ens-domain-field/ens-field.tsx
  ui/src/views/mint/nft-card/nft-card.tsx
Labels: bug, frontend

#207 refactor: contract billing storage is public and should be private
  contracts/contracts/FleekBilling.sol
Labels: bug, refactor

#210 refactor: drip stitches exports
  ui/src/components/card/card.styles.ts
  ui/src/components/core/avatar/avatar.styles.ts
  ui/src/components/core/button/button-content.styles.ts
  ui/src/components/core/button/button-icon.styles.ts
  ui/src/components/core/button/button-spinner.styles.ts
  ui/src/components/core/button/button-spinner.tsx
  ui/src/components/core/button/button.styles.ts
  ui/src/components/core/icon/icon.styles.ts
  ui/src/components/core/input/input-file.styles.ts
  ui/src/components/core/input/input.styles.ts
  ui/src/components/core/separator.styles.ts
  ui/src/components/core/text/text.styles.ts
  ui/src/components/form/form.styles.ts
  ui/src/components/layout/flex.styles.ts
  ui/src/components/layout/grid.styles.ts
  ui/src/components/layout/nav-bar/nav-bar.styles.ts
  ui/src/components/layout/page/page.styles.ts
  ui/src/components/layout/skeleton.styles.ts
  ui/src/components/layout/stepper/stepper.styles.ts
  ui/src/components/logo/logo.styles.ts
  ui/src/components/nfa-card/nfa-card.styles.ts
  ui/src/components/nfa-preview/nfa-preview.tsx
  ui/src/components/spinner/spinner.styles.ts
  ui/src/components/toast/toast.styles.tsx
  ui/src/theme/key-frames.ts
  ui/src/theme/themes.ts
  ui/src/views/explore/explore.styles.ts
  ui/src/views/explore/header.styles.ts
  ui/src/views/explore/list-nfas/results.styles.ts
Labels: enhancement

#195 chore: update config and commands to deploy to goerli
  contracts/.env.example
  contracts/.openzeppelin/goerli.json
  contracts/README.md
  contracts/deployments/goerli/FleekERC721.json
  contracts/deployments/goerli/FleekSVG.json
  contracts/deployments/goerli/proxy.json
  contracts/deployments/goerli/solcInputs/58255cfa14e848e4c855e2d02003b889.json
  contracts/deployments/sepolia/FleekERC721.json
  contracts/deployments/sepolia/solcInputs/9953f9ba3b3c3ea88082e5a0f127d034.json
  contracts/hardhat.config.ts
  contracts/package.json
  contracts/scripts/mint.js
  contracts/scripts/tokenURI.js
  contracts/scripts/upgrade.js
  contracts/scripts/verify.js
  ui/README.md
  ui/package.json
  ui/src/constants/env.ts
  ui/src/integrations/ethereum/contracts/FleekERC721.json
  ui/src/integrations/ethereum/ethereum.ts
  ui/src/integrations/ethereum/hooks/ethereum-hooks.tsx
  ui/src/providers/connectkit-provider.tsx
  ui/src/views/mint/mint-stepper.tsx
  ui/src/views/mint/nfa-step/form-step/mint-form.tsx
  ui/src/views/mint/preview-step/mint-preview.tsx
Labels: deployment

#179 chore: update the subgraph config & deploy the latest version
  subgraph/subgraph.yaml
Labels: deployment

#218 style: fix eslint errors for subgraph
  subgraph/src/access-control.ts
  subgraph/src/access-point.ts
  subgraph/src/approval.ts
  subgraph/src/contract.ts
  subgraph/src/fleek-nfa.ts
  subgraph/src/metadata-update.ts
  subgraph/src/mint.ts
  subgraph/src/transfer.ts
  subgraph/tests/matchstick/access-points/change-access-point-creation-status.test.ts
  subgraph/tests/matchstick/access-points/change-access-point-name-verify.test.ts
  subgraph/tests/matchstick/helpers/utils.ts
  subgraph/tests/matchstick/owner.test.ts
  subgraph/tests/matchstick/transfer.test.ts
Labels: quality-of-life, backend, refactor

#227 feat: UI create functionality to resolve address
  ui/src/components/index.ts
  ui/src/components/resolved-address/index.ts
  ui/src/components/resolved-address/resolved-address.styles.ts
  ui/src/components/resolved-address/resolved-address.tsx
  ui/src/store/features/ens/async-thunk/index.ts
  ui/src/store/features/ens/async-thunk/resolve-address.ts
  ui/src/store/features/ens/ens-slice.ts
  ui/src/store/features/ens/hooks/index.ts
  ui/src/store/features/ens/hooks/use-resolved-address.ts
  ui/src/store/features/ens/index.ts
  ui/src/store/features/index.ts
  ui/src/store/store.ts
  ui/src/views/components-test/components-test.tsx
Labels: enhancement, frontend

#233 test: remove all matchstick tests
  .github/workflows/subgraph.yml
  subgraph/README.md
  subgraph/matchstick.yaml
  subgraph/package.json
  subgraph/tests/matchstick/.latest.json
  subgraph/tests/matchstick/access-points/change-access-point-creation-status.test.ts
  subgraph/tests/matchstick/access-points/change-access-point-name-verify.test.ts
  subgraph/tests/matchstick/helpers/utils.ts
  subgraph/tests/matchstick/owner.test.ts
  subgraph/tests/matchstick/transfer.test.ts
Labels: test environment

#213 feat: add verifier input on mint form
  ui/graphql/queries.graphql
  ui/src/integrations/ethereum/hooks/ethereum-hooks.tsx
  ui/src/store/features/ens/async-thunk/resolve-address.ts
  ui/src/views/mint/nfa-step/form-step/mint-form.context.ts
  ui/src/views/mint/nfa-step/verify-step/verify-nfa-step.tsx
Labels: enhancement, frontend

#230 feat: UI indexed nfa view
  ui/graphql/queries.graphql
  ui/src/app.tsx
  ui/src/components/core/icon/icon-library.tsx
  ui/src/components/nfa-card/nfa-card.tsx
  ui/src/mocks/index.ts
  ui/src/mocks/nfa.ts
  ui/src/views/index.ts
  ui/src/views/indexed-nfa/fragments/aside.fragment.tsx
  ui/src/views/indexed-nfa/fragments/index.ts
  ui/src/views/indexed-nfa/fragments/main.fragment.tsx
  ui/src/views/indexed-nfa/fragments/skeleton.fragment.tsx
  ui/src/views/indexed-nfa/index.ts
  ui/src/views/indexed-nfa/indexed-nfa.context.tsx
  ui/src/views/indexed-nfa/indexed-nfa.styles.ts
  ui/src/views/indexed-nfa/indexed-nfa.tsx
Labels: enhancement, frontend

#236 refactor: ui explore view responsivity
  ui/src/app.tsx
  ui/src/components/layout/nav-bar/nav-bar.styles.ts
  ui/src/components/layout/page/page.styles.ts
  ui/src/components/nfa-card/nfa-card.styles.ts
  ui/src/components/nfa-card/nfa-card.tsx
  ui/src/views/explore/explore-header/explore-header.fragment.tsx
  ui/src/views/explore/explore-header/explore-header.styles.ts
  ui/src/views/explore/explore-header/index.ts
  ui/src/views/explore/explore-list/explore-list-container.tsx
  ui/src/views/explore/explore-list/explore-list.fragment.tsx
  ui/src/views/explore/explore-list/index.ts
  ui/src/views/explore/explore-list/nfa-list.fragment.tsx
  ui/src/views/explore/explore-list/nfa-list.styles.ts
  ui/src/views/explore/explore-list/nfa-list/index.ts
  ui/src/views/explore/explore-list/nfa-search.fragment.tsx
  ui/src/views/explore/explore-list/nfa-search.styles.ts
  ui/src/views/explore/explore-list/results.styles.ts
  ui/src/views/explore/explore.styles.ts
  ui/src/views/explore/explore.tsx
Labels: enhancement, frontend, refactor

#239 bug: contract verifier address sent on mint calls
  contracts/contracts/FleekERC721.sol
  contracts/package.json
  contracts/test/foundry/FleekERC721/Mint.t.sol
  contracts/test/hardhat/contracts/FleekERC721/minting.t.ts
  contracts/test/hardhat/scripts/deploy.ts
  contracts/yarn.lock
Labels: bug, contract

#244 feat: UI work on navbar responsivity
  ui/index.html
  ui/src/components/core/icon/icon-library.tsx
  ui/src/components/layout/nav-bar/connect-wallet-button.tsx
  ui/src/components/layout/nav-bar/logo.tsx
  ui/src/components/layout/nav-bar/nav-bar.styles.ts
  ui/src/components/layout/nav-bar/nav-bar.tsx
  ui/src/components/layout/nav-bar/navigation.tsx
  ui/src/components/layout/nav-bar/sidebar.tsx
  ui/src/components/logo/index.ts
  ui/src/components/logo/logo.styles.ts
  ui/src/components/logo/logo.tsx
  ui/src/hooks/index.ts
  ui/src/hooks/use-media-query.ts
  ui/src/theme/alpha-color.ts
  ui/src/theme/foundations/colors.ts
  ui/src/theme/index.ts
  ui/src/theme/themes.ts
Labels: frontend, refactor

#229 feat: Prisma integration and helper [serverless]
  serverless/.env.example
  serverless/README.md
  serverless/package.json
  serverless/prisma-setup/.env.example
  serverless/prisma-setup/.gitignore
  serverless/prisma-setup/client/index.ts
  serverless/prisma-setup/package.json
  serverless/prisma-setup/prisma/schema.prisma
  serverless/prisma-setup/tsconfig.json
  serverless/prisma-setup/yarn.lock
  serverless/prisma/schema.prisma
  serverless/serverless.yaml
  serverless/src/libs/query-prisma.ts
  serverless/yarn.lock
Labels: enhancement, backend

#232 feat: create smart contract helper for serverless
  serverless/package.json
  serverless/src/functions/builds/handler.ts
  serverless/src/libs/log-decoder.ts
  serverless/src/libs/nfa-contract.ts
  serverless/tsconfig.json
  serverless/yarn.lock
Labels: enhancement, backend

#231 feat: define submit build info interface and parameters [serverless]
  serverless/serverless.yaml
  serverless/src/functions/builds/handler.ts
Labels: enhancement, backend

#224 feat: MongoDB & Prisma [serverless]
  serverless/.env.example
  serverless/README.md
  serverless/examples/client/index.ts
  serverless/package.json
  serverless/prisma/schema.prisma
  serverless/serverless.yaml
  serverless/src/libs/query-prisma.ts
  serverless/tsconfig.json
  serverless/yarn.lock
Labels: enhancement, backend
