Repository fleekxyz/non-fungible-apps, pull requests merged in 2023-06, with the labels that each got.

#262 feat: lambda layers
  contracts/.openzeppelin/polygon-mumbai.json
  contracts/deployments/mumbai/FleekERC721.json
  contracts/deployments/mumbai/FleekSVG.json
  contracts/deployments/mumbai/proxy.json
  contracts/deployments/mumbai/solcInputs/9953f9ba3b3c3ea88082e5a0f127d034.json
  contracts/deployments/mumbai/solcInputs/ac10169ad2aa4aa05d336485b75a1a2f.json
  contracts/hardhat.config.ts
  serverless/.gitignore
  serverless/package.json
  serverless/scripts/prepare-libs-lambda-layer.sh
  serverless/scripts/prepare-node-modules-lambda-layer.sh
  serverless/scripts/prepare-prisma-client-lambda-layer.sh
  serverless/serverless.yaml
  serverless/src/libs/log-decoder.ts
  serverless/src/libs/nfa-contract.ts
Labels: enhancement, backend, deployment

#271 feat: verify hostname (load free certificate call to bunny cdn)
  serverless/serverless.yaml
  serverless/src/functions/apps/handler.ts
  serverless/src/functions/apps/index.ts
Labels: enhancement, backend

#272 feat: smart contract setTokenVerified calls through ethers
  serverless/package.json
  serverless/scripts/deploy.sh
  serverless/serverless.yaml
  serverless/src/functions/builds/handler.ts
  serverless/src/functions/mints/handler.ts
  serverless/src/libs/nfa-contract.ts
  serverless/src/libs/prisma.ts
  serverless/yarn.lock
Labels: enhancement, backend, refactor

#267 feat: add ipfs hash in mint form
  ui/src/integrations/ethereum/contracts/FleekERC721.json
  ui/src/integrations/ethereum/hooks/ethereum-hooks.tsx
  ui/src/integrations/ethereum/lib/fleek-erc721.ts
  ui/src/providers/connectkit-provider.tsx
  ui/src/views/components-test/combobox-test.tsx
  ui/src/views/mint/nfa-step/form-step/fields/index.ts
  ui/src/views/mint/nfa-step/form-step/fields/ipfs-hash-field.tsx
  ui/src/views/mint/nfa-step/form-step/mint-form.context.ts
  ui/src/views/mint/nfa-step/form-step/mint-form.tsx
  ui/src/views/mint/nfa-step/verify-step/select-verifier.tsx
Labels: frontend

#276 feat: add authentication [sls]
  serverless/src/functions/apps/handler.ts
  serverless/src/functions/builds/handler.ts
  serverless/src/functions/mints/handler.ts
Labels: enhancement, backend

#278 feat: dev environment backend setup
  contracts/deployments/qanet/FleekERC721.json
  contracts/deployments/qanet/FleekSVG.json
  contracts/deployments/qanet/proxy.json
  contracts/deployments/qanet/solcInputs/51265c9b241f9c7af77f823edadaae04.json
  contracts/deployments/sepolia/FleekERC721.json
  contracts/deployments/sepolia/FleekSVG.json
  contracts/deployments/sepolia/proxy.json
  contracts/deployments/sepolia/solcInputs/51265c9b241f9c7af77f823edadaae04.json
  contracts/hardhat.config.ts
  serverless/package.json
  serverless/scripts/deploy.sh
  serverless/serverless.yaml
  serverless/src/functions/apps/handler.ts
  serverless/src/functions/builds/handler.ts
  serverless/src/functions/mints/handler.ts
  serverless/src/libs/FleekERC721.json
  serverless/src/libs/bunnyCDN.ts
  serverless/src/libs/verify-signature.ts
  subgraph/subgraph.yaml
Labels: enhancement, backend, deployment, refactor

#281 docs: update readme to reflect new NFA design
  README.md
Labels: documentation, mvp
