Repository fleekxyz/non-fungible-apps, pull requests merged in 2023-05, with the labels that each got.

#237 docs: update readme, add serverless section.
  README.md
Labels: documentation

#248 fix: deployment store script
  contracts/scripts/deploy.js
  contracts/scripts/utils/deploy-store.js
Labels: bug, contract

#253 feat: verifications and mongo write operations
  contracts/contracts/FleekERC721.sol
  contracts/contracts/IERCX.sol
  contracts/test/foundry/FleekERC721/AccessControl.t.sol
  contracts/test/foundry/FleekERC721/Billing.t.sol
  contracts/test/foundry/FleekERC721/Constants.sol
  contracts/test/foundry/FleekERC721/GetToken.t.sol
  contracts/test/foundry/FleekERC721/Mint.t.sol
  contracts/test/foundry/FleekERC721/TestBase.sol
  contracts/test/foundry/FleekERC721/TokenURI.t.sol
  contracts/test/hardhat/contracts/FleekERC721/billing.t.ts
  contracts/test/hardhat/contracts/FleekERC721/collection-roles.t.ts
  contracts/test/hardhat/contracts/FleekERC721/ens.t.ts
  contracts/test/hardhat/contracts/FleekERC721/get-last-token-id.t.ts
  contracts/test/hardhat/contracts/FleekERC721/helpers/constants.ts
  contracts/test/hardhat/contracts/FleekERC721/helpers/events.ts
  contracts/test/hardhat/contracts/FleekERC721/helpers/fixture.ts
  contracts/test/hardhat/contracts/FleekERC721/minting.t.ts
  contracts/test/hardhat/contracts/FleekERC721/pausable.t.ts
  contracts/test/hardhat/contracts/FleekERC721/update-properties.t.ts
  contracts/test/hardhat/scripts/deploy.ts
  package.json
  serverless/README.md
  serverless/package.json
  serverless/prisma/schema.prisma
  serverless/src/functions/builds/handler.ts
  serverless/src/functions/mints/handler.ts
  serverless/src/libs/nfa-contract.ts
  serverless/src/libs/prisma.ts
  serverless/tsconfig.json
  serverless/yarn.lock
  subgraph/schema.graphql
  subgraph/src/metadata-update.ts
  subgraph/src/mint.ts
  subgraph/subgraph.yaml
  yarn.lock
Labels: documentation, enhancement, backend
